language: c
dist: xenial
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: |
  bash -ex .travis-opam.sh
env:
  global:
  - EXTRA_DEPS="dot-merlin-reader"
  - PINS="dot-merlin-reader.dev:."
  - ASSUME_ALWAYS_YES=YES
  matrix:
  - OCAML_VERSION=4.11
    PACKAGE=merlin
os:
  - linux
  - osx
  - freebsd
jobs:
  include:
  - os: linux
    env: OCAML_VERSION=4.02 PACKAGE=merlin TESTS=false
