name: Test
on:
  - push
  - pull_request

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        ocaml-version:
          - 4.10.0
          - 4.09.1
          - 4.08.1
          - 4.07.1
          - 4.06.1
          - 4.05.0
          - 4.04.2
          - 4.03.0
          - 4.02.3

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache
        uses: actions/cache@v1.1.2
        with:
          # A directory to store and save the cache
          path: ~/.opam
          # An explicit key for restoring and saving the cache
          key: ${{ runner.os }}-${{ matrix.ocaml-version }}-build

      - name: Use OCaml ${{ matrix.ocaml-version }}
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: ${{ matrix.ocaml-version }}

      - run: opam pin add merlin.dev . --no-action

      - run: opam depext merlin --yes --with-doc --with-test

      - run: opam install . --deps-only --with-doc --with-test

      - run: opam exec -- dune build

      - run: opam exec -- dune runtest
